name: Test

on:
  push:
    branches:
      - main
      - lab2
  pull_request:
    branches:
      - main
      - lab2

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Starting Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test
